### ISSUE TITLE
Crash when connected to the server

### ISSUE THREAD

**Issue by kulzz** [Tornamic/CoopAndreas#12]
GTA SA 1.0.0.0 US
Unhandled exception at 0x00734E5A in gta_sa.exe (+0x334e5a): 0xC0000005: Access violation reading location 0x00000008.
    Register dump:
        EAX: 0xC28C3281  EBX: 0x00000008  ECX: 0x00000000  EDX: 0x00734E50  
        EDI: 0x0177EA8C  ESI: 0x0177E9C0  EBP: 0x0177EA8C  EIP: 0x00734E5A  
        ESP: 0x0177E9A8  EFL: 0x00010202  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0177E9A8:  0177E9C0 0177EA8C 00000000 68CCC723 00000000 C28C3281
        0x0177E9C0:  0177EC0C 0177EA9C 00000000 00000000 649F4590 0F20BA00
        0x0177E9D8:  0B4D9F60 0177EA10 00000050 01990860 01990000 0000208F
        0x0177E9F0:  00000000 0B4D9F60 18EAE228 00000000 00000000 0000208F
        0x0177EA08:  0071A807 00000001 449FAD00 43A2AD75 1A615890 0177EB14
        0x0177EA20:  0177EA48 00000000 CCCCCCCC 0177EA40 68D1884B 0177EB1C
        0x0177EA38:  68D1D185 449FAD00 43A2AD75 68D1D18F 0177EC0C 0177F074
        0x0177EA50:  00000000 00000000 00000000 00000000 68DE7DB8 DDF7D444
        0x0177EA68:  0177EC1C 0177F074 00000000 00000045 68AC13C1 0177EC0C
        0x0177EA80:  CCCCCCCC CCCCCCCC 68D1E84D 0177EC0C 68B9AD16 00000000
        base: 0x01580000   top: 0x0177E9A8   bottom: 0x01780000
        
    Backtrace (may be wrong):
        =>0x00734E5A _Z35RwTexDictionaryFindHashNamedTextureP15RwTexDictionaryj+0xa in gta_sa.exe (+0x334e5a) (0x0177EA8C) 
          0x68B9AD16 DrawWeaponIcon+0x1f6 in CoopAndreasSA.dll (+0x2aad16) (0x0177EC0C) 
          0x68B9B474 CNetworkPlayerNameTag::Process+0x384 in CoopAndreasSA.dll (+0x2ab474) (0x0177EDD4) 
          0x68B3B3D0 <lambda_12b11c673c9f27feffb8d6d475e73a4a>::operator()+0x30 in CoopAndreasSA.dll (+0x24b3d0) (0x0177EEB4) 
          0x68B258EA std::invoke<<lambda_12b11c673c9f27feffb8d6d475e73a4a> &>+0x2a in CoopAndreasSA.dll (+0x2358ea) (0x0177EF88) 
          0x68B46967 std::_Func_impl_no_alloc<<lambda_12b11c673c9f27feffb8d6d475e73a4a>,void>::_Do_call+0x37 in CoopAndreasSA.dll (+0x256967) (0x0177F06C) 
          0x68B3E17A std::_Func_class<void>::operator()+0x5a in CoopAndreasSA.dll (+0x24e17a) (0x0177F158) 
          0x68B14D99 plugin::ArgPick<plugin::ArgTypes<> >::operator()<std::tuple<> >+0x59 in CoopAndreasSA.dll (+0x224d99) (0x0177F248) 
          0x68B3B4EC <lambda_259e50d27fd9201698473618dc8a5642>::operator()+0x5c in CoopAndreasSA.dll (+0x24b4ec) (0x0177F370) 
          0x68B21F5B std::for_each<std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<std::function<void __cdecl(void)>,unsigned int> > > >,<lambda_259e50d27fd9201698473618dc8a5642> >+0xab in CoopAndreasSA.dll (+0x231f5b) (0x0177F470) 
          0x68B3DDDE <lambda_fce75fa616daf668903ac5fd33318eda>::operator()+0x16e in CoopAndreasSA.dll (+0x24ddde) (0x0177F63C) 
          0x68B261E2 std::invoke<<lambda_fce75fa616daf668903ac5fd33318eda> &,std::function<void * __cdecl(void)> >+0x42 in CoopAndreasSA.dll (+0x2361e2) (0x0177F748) 
          0x68B47414 std::_Func_impl_no_alloc<<lambda_fce75fa616daf668903ac5fd33318eda>,void *,std::function<void * __cdecl(void)> >::_Do_call+0x44 in CoopAndreasSA.dll (+0x257414) (0x0177F830) 
          0x68B3E0A3 std::_Func_class<void *,std::function<void * __cdecl(void)> >::operator()+0xa3 in CoopAndreasSA.dll (+0x24e0a3) (0x0177F944) 
          0x68B512CA injector::function_hooker_manager<injector::scoped_call,injector::function_hooker_base<injector::scoped_call,5497491,void * (__cdecl*)(void),void *>,void *>::call_hooks+0x13a in CoopAndreasSA.dll (+0x2612ca) (0x0177FBC0) 
          0x68B50C57 injector::function_hooker_base<injector::scoped_call,5497491,void * (__cdecl*)(void),void *>::call_hooks+0x27 in CoopAndreasSA.dll (+0x260c57) (0x0177FC94) 
          0x68B50AC7 injector::function_hooker<injector::scoped_call,5497491,void * __cdecl(void)>::call+0x27 in CoopAndreasSA.dll (+0x260ac7) (0x0177FD68) 
          0x0053E298 _Z13Render2dStuffv+0x68 in gta_sa.exe (+0x13e298) (0x0177FD84) 
          0x0053EB17 _Z4IdlePv+0x1f7 in gta_sa.exe (+0x13eb17) (0x0177FD90)

**Comment by kulzz** [comment]
![image](https://github.com/user-attachments/assets/057b2bcf-444d-42b8-b28c-bb89be61926a)

**Comment by Tornamic** [comment]
already in tasklist
