### ISSUE TITLE
Краш при попытке стрельбы из узи

### ISSUE THREAD

**Issue by kulzz** [Tornamic/CoopAndreas#13]
GTA SA 1.0.0.0 US
Unhandled exception at 0x689463E6 in CoopAndreasSA.dll (+0x2963e6): 0xC0000005: Access violation reading location 0x00000036.
    Register dump:
        EAX: 0x00000000  EBX: 0x00C8C1E8  ECX: 0x01CD87F0  EDX: 0x00000001  
        EDI: 0x0177FA74  ESI: 0x00000000  EBP: 0x0177FA80  EIP: 0x689463E6  
        ESP: 0x0177F94C  EFL: 0x00010246  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0177F94C:  E0ABC31D 13C5ADE0 00000000 00C8C1E8 01CD87F0 004A3FE4
        0x0177F964:  01CD87F0 04998100 0177FA64 01CD87F0 00000225 004A4038
        0x0177F97C:  04998100 0177FA70 BF800000 0177FA64 00000000 04998100
        0x0177F994:  049981C0 00000000 00000000 00000000 00000000 00000000
        0x0177F9AC:  00000000 00000000 00000000 00000000 00000000 BEDAB200
        0x0177F9C4:  00000000 3F800000 00000000 0000000B 00000000 41292A70
        0x0177F9DC:  00000000 13C5ADE0 006E6303 13C5ADE0 00000000 13C5ADE0
        0x0177F9F4:  00C8C1E8 C49F4C98 41C4CA3D 41C5FDD5 00000003 00000003
        0x0177FA0C:  0000000B 0177FA70 BF800000 3F800000 CCCCCCCC CCCCCCCC
        0x0177FA24:  CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
        base: 0x01580000   top: 0x0177F94C   bottom: 0x01780000
        
    Backtrace (may be wrong):
        =>0x689463E6 CWeapon__DoBulletImpact_Hook+0xc6 in CoopAndreasSA.dll (+0x2963e6) (0x0177FA80) 
          0x007412E4 _ZN7CWeapon14FireInstantHitEP7CEntityP7CVectorS3_S1_S3_S3_bb+0x17d4 in gta_sa.exe (+0x3412e4) (0x0177FB2C) 
          0x00420C74 CCamera_IsSphereVisible_Internal+0x34 in gta_sa.exe (+0x20c74) (0x0177FB94) 
          0x0049E3D5 _ZN14CTrafficLights18DisplayActualLightEP7CEntity+0x925 in gta_sa.exe (+0x9e3d5) (0x0177FBD4) 
          0x00533522 TransformFromObjectSpace__7CEntityRC7CVector+0x32 in gta_sa.exe (+0x133522) (0x0177FBD8) 
          0x0177FBF4 in unknown (+0x177fbf4) (0x0177FC50) 
          0x0074254D _ZN7CWeapon4FireEP7CEntityP7CVectorS3_S1_S3_S3_+0x24d in gta_sa.exe (+0x34254d) (0x0177FCC0) 
          0x0061ECD2 _ZN17CTaskSimpleUseGun7FireGunEP4CPedb+0x1c2 in gta_sa.exe (+0x21ecd2) (0x0177FCFC) 
          0x00624F12 _ZN17CTaskSimpleUseGun14SetPedPositionEP4CPed+0x42 in gta_sa.exe (+0x224f12) (0x0177FD14) 
          0x00601AA1 _ZN16CPedIntelligence21ProcessAfterPreRenderEv+0xf1 in gta_sa.exe (+0x201aa1) (0x0177FD44) 
          0x00707FBB _ZN8CShadows24RenderExtraPlayerShadowsEv+0x1b in gta_sa.exe (+0x307fbb)

**Comment by kulzz** [comment]
![image](https://github.com/user-attachments/assets/b747b5a3-a4a3-4dfb-92dd-432f2e1ea9ef)
[gta_sa.exe_2024-09-01_13-58-24.log](https://github.com/user-attachments/files/16828672/gta_sa.exe_2024-09-01_13-58-24.log)
Краш при стрельбе в ту же секунду как заходит новый игрок

**Comment by kulzz** [comment]
![image](https://github.com/user-attachments/assets/c7f32bb9-f777-42df-bbce-3d02379ec1eb)
краш как только другой игрок взял винтовку в руки

**Comment by Tornamic** [comment]
fixed
