### ISSUE TITLE
[Question] What is this project for ?

### ISSUE THREAD

**Issue by LYZENCORE-9** [Tornamic/CoopAndreas#16]
it's a mod for something in game or a new multiplayer mod for GTA San Andreas ?

**Comment by Tornamic** [comment]
Hi, this is a network multiplayer mod written from scratch with priority on synchronization of NPCs, traffic, cooperative missions, etc. News, screenshots, videos, etc. can be found here https://discord.gg/Z3ugSgFJMU

**Comment by LYZENCORE-9** [comment]
nice work bro , there is any progress ?

**Comment by Tornamic** [comment]
@LYZENCORE-9 https://youtu.be/Zg_XrgLW2yQ

**Comment by LYZENCORE-9** [comment]
good job bro , you did good work but there is a question , why you are using enet library , use RakNET it's better , enet is abandoned and it have many issues

**Comment by LYZENCORE-9** [comment]
and give the CMakeLists.txt , i want to try a tweak in packets in your project

**Comment by Tornamic** [comment]
@LYZENCORE-9 interesting question.

just clone repo and open .sln using VS2022

**Comment by LYZENCORE-9** [comment]
the problem is i don't like microsoft development environment tools like Visual Studio because they are useless

**Comment by Tornamic** [comment]
@LYZENCORE-9 nice, how i can contact you?

**Comment by LYZENCORE-9** [comment]
my official discord for **CHILLING** is : _distroxyde_

i can give you my official discord for business and chilling but i forget it :laughing:
