### ISSUE TITLE
Смэрть

### ISSUE THREAD

**Issue by xKEKx1244** [Tornamic/CoopAndreas#8]
При смерти игра рипнулась

GTA SA 1.0.0.0 US
Unhandled exception at 0x42480000 in gta_sa.exe: 0xC0000005: Access violation reading location 0x42480000.
    Register dump:
        EAX: 0x0096908C  EBX: 0x00000001  ECX: 0x1435D4D0  EDX: 0x00863C40  
        EDI: 0x00000000  ESI: 0x1435D4D0  EBP: 0x1435D938  EIP: 0x42480000  
        ESP: 0x0177F06C  EFL: 0x00210212  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0177F06C:  0056A39D 00000002 00B7CF28 00000000 0000003F 00000000
        0x0177F084:  04554ED0 00000000 0000006E 00000000 00000000 00000000
        0x0177F09C:  00442F0D 0177F0E4 457A0000 00000001 00000000 00000000
        0x0177F0B4:  0177F200 00000001 0000000F 000007C5 0072D9B5 450C6510
        0x0177F0CC:  C49DEB51 41BF9F52 00000000 00000000 0177F200 00000001
        0x0177F0E4:  450C6510 C49DEB51 41BF9F52 450C6510 C49DEB51 41BF9F52
        0x0177F0FC:  450C6510 C49DEB51 41BF9F52 0053C122 0177F200 0177F128
        0x0177F114:  00000000 A3265343 0177F200 5C40E446 5B88D227 0177F2D4
        0x0177F12C:  0177F3C0 00000000 CCCCCCCC 0177F244 CCCCCCCC CCCCCCCC
        0x0177F144:  0177F244 5B886829 0177F23C CCCCCCCC CCCCCCCC 0177F264
        base: 0x01580000   top: 0x0177F06C   bottom: 0x01780000
        
    Backtrace (may be wrong):
        =>0x42480000 in unknown (+0x42480000) (0x0177F068) 
          0x0056A39D _ZN6CWorld26ClearExcitingStuffFromAreaERK7CVectorfh+0x2cd in gta_sa.exe (+0x16a39d) (0x0177F098) 
          0x00442F0D _ZN10CGameLogic6UpdateEv+0x43d in gta_sa.exe (+0x42f0d)

**Comment by Tornamic** [comment]
i know about this bug
