### ISSUE TITLE
Crash due trying to shoot out of a pistol

### ISSUE THREAD

**Issue by kulzz** [Tornamic/CoopAndreas#9]
GTA SA 1.0.0.0 US
Unhandled exception at 0x68B863E6 in CoopAndreasSA.dll (+0x2963e6): 0xC0000005: Access violation reading location 0x00000036.
    Register dump:
        EAX: 0x00000000  EBX: 0x00C8BF48  ECX: 0x22AC4C18  EDX: 0x00000001  
        EDI: 0x0177FA74  ESI: 0x00000000  EBP: 0x0177FA80  EIP: 0x68B863E6  
        ESP: 0x0177F94C  EFL: 0x00010246  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0177F94C:  9A50C0A5 15C5A988 00000000 00C8BF48 22AC4C18 004A3FE4
        0x0177F964:  22AC4C18 01878100 0177FA64 22AC4C18 00000B02 004A4038
        0x0177F97C:  01878100 0177FA70 BF800000 0177FA64 00000000 01878100
        0x0177F994:  018781C0 00000000 00000000 00000000 00000000 00000000
        0x0177F9AC:  00000000 00000000 00000000 00000000 00000000 BE8F72C0
        0x0177F9C4:  00000000 3F800000 00000000 0000000B 00000000 412B846A
        0x0177F9DC:  00000000 15C5A988 006E6303 15C5A988 00000000 15C5A988
        0x0177F9F4:  00C8BF48 C49A538B 41E36073 41E4C8DC 00000003 00000003
        0x0177FA0C:  0000000B 0177FA70 BF800000 3F800000 CCCCCCCC CCCCCCCC
        0x0177FA24:  CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
        base: 0x01580000   top: 0x0177F94C   bottom: 0x01780000
        
    Backtrace (may be wrong):
        =>0x68B863E6 CWeapon__DoBulletImpact_Hook+0xc6 in CoopAndreasSA.dll (+0x2963e6) (0x0177FA80) 
          0x007412E4 _ZN7CWeapon14FireInstantHitEP7CEntityP7CVectorS3_S1_S3_S3_bb+0x17d4 in gta_sa.exe (+0x3412e4) (0x0177FB2C) 
          0x00420C74 CCamera_IsSphereVisible_Internal+0x34 in gta_sa.exe (+0x20c74) (0x0177FB30) 
          0x0059BDF4 InvertMatrix+0x24 in gta_sa.exe (+0x19bdf4) (0x0177FBBC) 
          0x0049DD51 _ZN14CTrafficLights18DisplayActualLightEP7CEntity+0x2a1 in gta_sa.exe (+0x9dd51) (0x0177FBD0) 
          0x0049DE1A _ZN14CTrafficLights18DisplayActualLightEP7CEntity+0x36a in gta_sa.exe (+0x9de1a)

**Comment by Tornamic** [comment]
fixed
